# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gKO9f5JDApM3S6QT-O7E4kHNgeNmhJ8M
"""

import requests
from bs4 import BeautifulSoup

# Specify the URL of the webpage to scrape
url = 'https://www.bbc.com/sport/football/scores-fixtures'

# Send a GET request to the webpage and get the HTML response
response = requests.get(url)

# Parse the HTML response using BeautifulSoup
soup = BeautifulSoup(response.text, 'html.parser')

# Find the container that holds the scores
score_container = soup.find('div', {'class': 'qa-match-block'})

# Loop through each score and extract the home team, away team, and score
for score in score_container.find_all('div', {'class': 'sp-c-fixture__wrapper'}):
    home_team = score.find('span', {'class': 'sp-c-fixture__team--home'}).text.strip()
    away_team = score.find('span', {'class': 'sp-c-fixture__team--away'}).text.strip()
    score = score.find('span', {'class': 'sp-c-fixture__block'}).text.strip()
    
    # Print the extracted data
    print(f'{home_team} {score} {away_team}')
